### ISSUE TITLE
feature request: filter to suppress "mit Untertitel"

### ISSUE THREAD

**Issue by supervisitor** [mediathekview/MediathekView#535]
sometimes there are movies twice in the list, with and without "mit Untertitel". the filter should have a feature to suppress the unwanted version

**Comment by vitusson** [comment]
Das kann man ganz einfach wie so vieles andere auch über die Blacklist wegfiltern…
`
#:(Hörfassung:?|AD \|) .*|.*(mit |\[|\(|- )(AD|Audiodes(k|c)ription|Hörfassung|Untertitel)(\)|\]|\, .*\) `

**Comment by supervisitor** [comment]
but a "click" in the filter list would be a benefit for less experienced users!
because what else is the filter list for? otherwise the filter list could be omitted.

**Comment by alex1702** [comment]
Eventuell wäre mal eine Filtersammlung oder Vorlagen im Programm ganz gut. Nicht jeder kann gut mit Regex umgehen oder hat da Bock drauf sich mit rumzuärgern ^^

**Comment by supervisitor** [comment]
Isn't that what I mean?!
Excuse me, but you are one of the IT people, so you are not the target group. For everyone else... a "click" in the filter list would be just perfect.
Not everyone likes the CLI and knows how "regex" works.

**Comment by derreisende77** [comment]
A click in the filter list may not be "just perfect"... The filter list is for all the use cases specified through the text of the checkboxes…it is an offering to simplify work. Not more, not less.
Your problem basically only applies to ARTE sender. Implementing the filter in a way you suggested would be _inconsistent_ as it would filter too many entries.
**Background:**
In MV there are regular films without subtitles, films with subtitles provided by URL and films with “burned in” subtitles which do not have a subtitle URL.
In order to make the suggested filter work it would also need to filter all entries which do have a subtitle URL because they do have subtitles (according to definition). This would make the resulting list really small…

What I could offer is the following (although this will apply only to 386 films out of 373246 films in my list as of today):
A checkbox named “Filme mit eingebrannten Untertiteln ausblenden”
This would hide all entries with “burned in” subtitles WITHOUT touching the regular films which may have a subtitle URL. This will hide most of the films ”(mit Untertitel)” who seem to disturb you.

Still, as @vitusson suggested the use of the blacklist would be a lot better in this use case as it is a lot more configurable (and modifiable). Getting help for syntax should be no problem in the forum and google helps a lot with syntax as well.

**Comment by supervisitor** [comment]
I just suggested a checkbox to hide movies with subtitles, similar to the one to suppress "Gebärdensprache".
Whether these are burned in or separate, that's probably not important for me or the user. My intention was to remove the movies with subtitles from the list, even though I described it differently using my example. So this seemed to me simply more easy-to-understand.
My concrete scenario: my father learns German with watching movies from the library. He is watching the same movie more than once. But if he catches one with subtitles, he doesn't listen anymore, then he reads. And he should listen in it to understand, he should not read the subtitles.
My father is now 68 years old, he doesn't want to learn regex, but he can search and load movies with MV. And he should do everything himself. That I can handle regex, you can maybe imagine. 😇  And from my own personal situation I decided: maybe there are others who would like to have the same?!

**Comment by derreisende77** [comment]
As I said, I could provide a filter checkbox to remove films with subtitles **burned in**, but not for regular films. 
If you download a regular film which has the subtitle checkbox activated in the filmtab does not normally download the subtitle file unless requested. This is done in the download dialog which contains a chechbox "Untertitel speichern ...".
Therefore I guess I will implement the filter checkbox against burned in films and the rest has to be done by the user not to download subtitles for a movie.

Hope this would help?
