### ISSUE TITLE
Add confirmation of removal of entries from Downloads list

### ISSUE THREAD

**Issue by puhli** [mediathekview/MediathekView#620]
After accidentally removing a large list of scheduled downloads I noticed that MediathekView is missing a prompt that asks for a confirmation before actually performing the removal.

The application must show a modal dialog to ask the user to confirm the action. If the user confirms the downloads are removed. If not the action is aborted.

**Comment by derreisende77** [comment]
In order to delete more than two downloads at once you either have to click the trash button or use the corresponding menu. The context menu will only delete one entry.
That said, if you *intentionally* click on the menu entry or the toolbar button, the program expects *you know* what you are doing. And it will fulfill your wish without further questions. 
Personally, I tried your PR and I got quickly pissed by being asked every time I needed to clean my download list due to my abos whether I really want to delete the entry or not. Given the age of the application and current way of working I do expect a huge uproar in the forum that I/we destroyed their current workflow.
Therefore I will not merge that change in.
