### ISSUE TITLE
[Enhancement] Readability: Make font in download progress column the same size as other columns

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#698]
Screenshot 1 shows the font size in the progress column during a download. It is smaller than the font size in the other columns and not very well readable.
Screenshot 2 shows the font size after the download has finished. It is now the same size as the other columns.

Please make the font size during downloading equally large as the other columns, that would make the progress more readable during Download. The blue download progress in the background would still be very very visible, even with the larger font size.

**Screenshot 1:**
![grafik](https://github.com/mediathekview/MediathekView/assets/109863013/82b5552d-56ec-4421-a020-ed48a6418ea6)

**Screenshot 2**
![grafik](https://github.com/mediathekview/MediathekView/assets/109863013/c5367494-47cd-4aa4-8182-a55b91a9d3dd)

**Comment by derreisende77** [comment]
The progress text is part of the progress control and therefore must fit into it -> smaller font than the rest. This is intentional and will not be fixed. Besides that in MV 14 there will be no more text shown in the progress control as it provides all the information.
The white color highlighting is done by the platform-specific UI settings and not by our program - and it will depend on whether you are using dark mode or not. It will also remain this way. If the background colors do disturb you you can change them in the settings dialog yourself.
